[build]
builder = "NIXPACKS"
buildCommand = """
apt-get update && apt-get install -y python3-dev
python -m pip install --upgrade pip
pip install --no-cache-dir setuptools wheel
pip install --no-cache-dir -r requirements.txt
"""

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.9.16"
NIXPACKS_PYTHON_VERSION = "3.9.16" 